version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive

  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: context-as-argument
          disabled: false
          arguments:
            - allow-types-before: "*testing.T"

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
